### ISSUE TITLE
Discord won't work after an update.

### ISSUE THREAD

**Issue by ghost** [elmarco/discord-app#2]
Today I received an update for Discord; It updated itself, and after that it failed to start.
It closes itself when blank Discord window appears after the startup pop-up window is shown.
The output which most likely points to the error when running from CLI is:

```
exception_ptr not yet implemented
[WebContents] crashed... reloading
Feature redeclared; is this a duplicate flag?  voice_sound_stop_loop
Feature redeclared; is this a duplicate flag?  voice_relative_sounds
Feature redeclared; is this a duplicate flag?  voice_panning
Feature redeclared; is this a duplicate flag?  voice_multiple_connections
Feature redeclared; is this a duplicate flag?  media_devices
Feature redeclared; is this a duplicate flag?  media_video
exception_ptr not yet implemented
```

**Comment by Empathetic** [comment]
It's actually more output than that on the terminal, the flatpak is outputting all of these lines, then it's crashing:
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Discord 0.0.2
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Install path: /home/USERDIR/.var/app/com.discordapp.Discord/config/discord/0.0.2/modules
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
exception_ptr not yet implemented
[WebContents] crashed... reloading
Feature redeclared; is this a duplicate flag?  voice_sound_stop_loop
Feature redeclared; is this a duplicate flag?  voice_relative_sounds
Feature redeclared; is this a duplicate flag?  voice_panning
Feature redeclared; is this a duplicate flag?  voice_multiple_connections
Feature redeclared; is this a duplicate flag?  media_devices
Feature redeclared; is this a duplicate flag?  media_video
exception_ptr not yet implemented
